include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    directives_ordering: false
    always_use_package_imports: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_constructors_first: false
